# Generated by Django 6.0 on 2026-01-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_head_image_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='head_image',
        ),
    ]
